# Generated by Django 6.1 on 2026-08-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_approvallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='True right after Emergency Services intake, where a staff-generated password may have been seen by someone other than the patient (a companion reading it off screen, e.g.). Forces a password change on next login rather than trusting that handoff was private.'),
        ),
    ]
