# Generated by Django 6.1 on 2026-08-12 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_approvallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_type', models.CharField(choices=[('HEART_RATE', 'Heart Rate (bpm)'), ('BLOOD_PRESSURE', 'Blood Pressure (mmHg)'), ('TEMPERATURE', 'Temperature (°C)'), ('OXYGEN_SATURATION', 'Oxygen Saturation (%)'), ('GLUCOSE', 'Blood Glucose (mg/dL)'), ('OTHER', 'Other')], max_length=30)),
                ('value', models.CharField(help_text="e.g. '72' for heart rate, or '120/80' for blood pressure", max_length=50)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(help_text='When the device captured this reading.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_readings', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
